apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: open-flights-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open-flights-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
